# Generated by Django 2.2.6 on 2019-10-06 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.BooleanField(default=False, unique=True)),
                ('email', models.EmailField(default=False, max_length=254)),
                ('telegram', models.CharField(max_length=40)),
                ('is_subscribed', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('send_to_telegram', models.BooleanField(default=False)),
                ('send_to_email', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sport', models.CharField(max_length=254)),
                ('league', models.CharField(max_length=254)),
                ('teams', models.CharField(max_length=254)),
                ('prediction', models.CharField(max_length=254)),
                ('match_result', models.CharField(max_length=254)),
                ('prediction_result', models.CharField(blank=True, choices=[('Won', 'Won'), ('Lose', 'Lose')], max_length=10, null=True)),
                ('link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionBK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('coefficient', models.CharField(max_length=254)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Prediction')),
            ],
        ),
    ]
