# Generated by Django 2.2.6 on 2019-10-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191007_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='user',
        ),
        migrations.AddField(
            model_name='link',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='oddsportal_password',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='oddsportal_username',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
