# Generated by Django 2.2.6 on 2019-10-09 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191008_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prediction',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
