# Generated by Django 2.2.6 on 2019-10-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191009_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prediction',
            options={'ordering': ['-teams']},
        ),
    ]
