# Generated by Django 2.2.6 on 2019-10-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191009_0825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prediction',
            old_name='link',
            new_name='link_to_match',
        ),
        migrations.AddField(
            model_name='prediction',
            name='link_to_odd',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
