# Generated by Django 2.2.6 on 2019-10-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_prediction_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Link'),
        ),
    ]
