# Generated by Django 2.2.6 on 2019-10-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20191015_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='link',
            name='current_bank',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='link',
            name='lose',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='profit_for_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='link',
            name='won',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prediction',
            name='bet_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='prediction',
            name='bet_coefficient',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
