# Generated by Django 2.2.6 on 2019-10-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191016_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-profit_for_month', '-bank', '-won', 'lose']},
        ),
        migrations.AddField(
            model_name='prediction',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
