# Generated by Django 2.2.6 on 2019-10-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191016_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionbk',
            options={'ordering': ['coefficient']},
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
