# Generated by Django 2.2.6 on 2019-10-26 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191016_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictionbk',
            options={'ordering': ['coefficient']},
        ),
    ]
