# Generated by Django 2.2.6 on 2019-10-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191028_1108'),
        ('app', '0020_auto_20191026_1411'),
    ]

    operations = [
    ]
