# Generated by Django 2.2.6 on 2019-10-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_merge_20191028_1110'),
        ('app', '0021_auto_20191028_1112'),
    ]

    operations = [
    ]
